### PR TITLE
Use the Jinja2 compiler syntax

### PR DESCRIPTION
**Pull request by leouieda**
I removed the python build dependency on Windows since I saw on other feedstocks that this wasn't necessary with the new compilers.

### CODE REVIEW

**Comment by leouieda** [comment]
@conda-forge-admin, please re-render

**Comment by leouieda** [comment]
@conda-forge-admin, please re-render

**Comment by leouieda** [comment]
@jakirkham @scopatz @sebastian-luna-valero @saraedum the builds are passing on this so I'm guessing the migration was successful. Is there any other check that needs to be run?

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
